### ISSUE TITLE
Release v2.15.0 doesn't contain build artifacts, missing /bin folder.

### ISSUE THREAD

**Issue by jtdevops** [datastack-net/dockerized#24]
The latest release v2.15.0 doesn't contain build artifacts, missing /bin folder.

**Comment by boukeversteegh** [comment]
Ouch, thanks for reporting! Right on it 😊

**Comment by boukeversteegh** [comment]
Fixed!

https://github.com/datastack-net/dockerized/releases/tag/v2.15.1
