### ISSUE TITLE
Support for Apple Silicon (aarch64)

### ISSUE THREAD

**Issue by halostatue** [datastack-net/dockerized#32]
The script `bin/dockerized` isn’t set up to be able to build for Apple Silicon. Modifying the architectures should _probably_ include a detection for ~`aarch64`~ `arm64`, the arm64 / aarch64 target for GO.

https://github.com/datastack-net/dockerized/blob/master/bin/dockerized#L55-L63

**Comment by halostatue** [comment]
```bash
diff --git c/bin/dockerized i/bin/dockerized
index aafa2b86b370..105ebd4f4764 100755
--- c/bin/dockerized
+++ i/bin/dockerized
@@ -59,7 +59,9 @@ x86_64)
 i*86)
   DOCKERIZED_COMPILE_GOARCH=386
   ;;
-
+arm64 | aarch64)
+  DOCKERIZED_COMPILE_GOARCH=arm64
+  ;;
 esac
 
 if [ "$DOCKERIZED_COMPILE" ] || [ ! -f "$DOCKERIZED_BINARY" ]; then
```

**Comment by boukeversteegh** [comment]
Hi, thank you for reporting! Would you mind to make a PR for your suggested change?
If it works on your system then I can just merge it right away. Not able to do it myself right now as I'm out.
